version: "3"
services:
  redis:
    image: "redis:alpine"
  cliapp:
    build:
      context: .
      dockerfile: Dockerfile.cliapp
    image: cliappimg
  webapp:
     build:
      context: .
      dockerfile: Dockerfile.webapp
     image: webappimg
     ports:
      - "8080:80"